export const getSports = (sport: string) => {
    switch (sport.toLowerCase()) {
        case 'arc':
            return require('@/assets/logo/sports/arc.png');
        case 'atletisme': 
            return require('@/assets/logo/sports/atletisme.png');
        case 'badminton':
            return require('@/assets/logo/sports/badminton.png');
        case 'baseball':
            return require('@/assets/logo/sports/baseball.png');
        case 'basket':
            return require('@/assets/logo/sports/basket.png');
        case 'bowling':
            return require('@/assets/logo/sports/bowling.png');
        case 'boxe':
            return require('@/assets/logo/sports/boxe.png');
        case 'course':
            return require('@/assets/logo/sports/course.png');
        case 'crossfit':
            return require('@/assets/logo/sports/crossfit.png');
        case 'danse':
            return require('@/assets/logo/sports/danse.png');
        case 'equitation':
            return require('@/assets/logo/sports/equitation.png');
        case 'escrime':
            return require('@/assets/logo/sports/escrime.png');
        case 'football':
            return require('@/assets/logo/sports/football.png');
        case 'golf':
            return require('@/assets/logo/sports/golf.png');
        case 'gymnastique':
            return require('@/assets/logo/sports/gymnastique.png');
        case 'judo':
            return require('@/assets/logo/sports/judo.png');
        case 'karate':
            return require('@/assets/logo/sports/karate.png');
        case 'lutte':
            return require('@/assets/logo/sports/lutte.png');
        case 'moto':
            return require('@/assets/logo/sports/moto.png');
        case 'musculation':
            return require('@/assets/logo/sports/musculation.png');
        case 'paddle':
            return require('@/assets/logo/sports/paddle.png');
        case 'paintball':
            return require('@/assets/logo/sports/paintball.png');
        case 'peche':
            return require('@/assets/logo/sports/peche.png');
        case 'pilate':
            return require('@/assets/logo/sports/pilate.png');
        case 'pingpong':
            return require('@/assets/logo/sports/pingpong.png');
        case 'rugby':
            return require('@/assets/logo/sports/rugby.png');
        case 'skateboard':
            return require('@/assets/logo/sports/skateboard.png');
        case 'ski':
            return require('@/assets/logo/sports/ski.png');
        case 'surf':
            return require('@/assets/logo/sports/surf.png');
        case 'tennis':
            return require('@/assets/logo/sports/tennis.png');
        case 'voile':
            return require('@/assets/logo/sports/voile.png');
        case 'volley':
            return require('@/assets/logo/sports/volley.png');    
        case 'yoga':
            return require('@/assets/logo/sports/yoga.png');
        default:
            return require('@/assets/logo/apple.png');
    }
};
